import { useState, useEffect } from 'react';
import supabase from '../../supabaseClient';
import { useData } from '../../contexts/DataContext';
import { Calendar, Users, CreditCard, TrendingUp, Clock, CheckCircle, Building2, Loader2, ArrowRight } from 'lucide-react';
import { formatCurrency } from '../../utils/currency';
import { Link } from 'react-router-dom';

export default function AdminDashboard() {
  // We still use units from DataContext since they are relatively static
  const { units } = useData();

  // Local state for live database records
  const [bookings, setBookings] = useState<any[]>([]);
  const [inquiries, setInquiries] = useState<any[]>([]);
  // Note: Payments are still stubbed to an empty array here until your Supabase payments table is ready.
  const [payments, setPayments] = useState<any[]>([]); 
  const [isLoading, setIsLoading] = useState(true);

  // Fetch live dashboard data
  useEffect(() => {
    const fetchDashboardData = async () => {
      try {
        // Fetch Reservations
        const { data: bookingData, error: bookingError } = await supabase
          .from('reservations')
          .select('*')
          .order('created_at', { ascending: false });
        if (bookingError) throw bookingError;

        // Fetch Inquiries (Messages)
        const { data: inquiryData, error: inquiryError } = await supabase
          .from('messages')
          .select('message_id, status, subject, name, date')
          .order('date', { ascending: false });
        if (inquiryError) throw inquiryError;

        setBookings(bookingData || []);
        setInquiries(inquiryData || []);
        // setPayments(paymentsData || []); // Uncomment when payments table exists

      } catch (error) {
        console.error("Error fetching admin dashboard data:", error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchDashboardData();
  }, []);

  const today = new Date().toISOString().split('T')[0];
  
  // Basic Stats
  const todayBookings = bookings.filter(b => b.created_at.startsWith(today));
  const pendingBookings = bookings.filter(b => b.status === 'pending');
  const approvedBookings = bookings.filter(b => b.status === 'approved' || b.status === 'confirmed');
  
  // Revenue Stats (Derived from bookings paid_amount for now, until payments table is fully wired)
  const totalRevenue = bookings.reduce((sum, b) => sum + Number(b.paid_amount || 0), 0);
  const pendingPayments = payments.filter(p => p.status === 'unpaid'); // Waiting on actual payments logic
  
  const openInquiries = inquiries.filter(i => i.status === 'open');

  // Top performing properties
  const unitBookings = units.map(unit => {
    const unitReservations = bookings.filter(b => b.unit_id === unit.id);
    return {
      ...unit,
      bookingCount: unitReservations.length,
      // Total Revenue specifically generated by this unit
      revenue: unitReservations
        .filter(b => b.status !== 'cancelled' && b.status !== 'rejected')
        .reduce((sum, b) => sum + Number(b.total_amount || 0), 0)
    };
  }).sort((a, b) => b.revenue - a.revenue).slice(0, 5);

  // Recent bookings (top 5)
  const recentBookings = bookings.slice(0, 5);

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center h-96">
        <Loader2 className="size-8 text-blue-600 animate-spin mb-4" />
        <p className="text-gray-500 text-lg">Loading dashboard data...</p>
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div>
        <h1 className="mb-2 text-2xl font-bold text-gray-900">Admin Dashboard</h1>
        <p className="text-gray-600">Overview of your rental management system</p>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm">
          <div className="flex items-center justify-between mb-2">
            <p className="text-sm font-medium text-gray-600">Today's Reservations</p>
            <Calendar className="size-5 text-blue-600" />
          </div>
          <p className="text-gray-900 text-2xl font-bold">{todayBookings.length}</p>
          <p className="text-xs text-gray-500 mt-1">Requests received today</p>
        </div>

        <div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm">
          <div className="flex items-center justify-between mb-2">
            <p className="text-sm font-medium text-gray-600">Pending Approvals</p>
            <Clock className="size-5 text-yellow-600" />
          </div>
          <p className="text-gray-900 text-2xl font-bold">{pendingBookings.length}</p>
          <Link to="/admin/bookings" className="text-xs font-medium text-blue-600 hover:text-blue-700 mt-1 inline-block">
            Review reservations →
          </Link>
        </div>

        <div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm">
          <div className="flex items-center justify-between mb-2">
            <p className="text-sm font-medium text-gray-600">Total Revenue Collected</p>
            <TrendingUp className="size-5 text-green-600" />
          </div>
          <p className="text-gray-900 text-2xl font-bold">{formatCurrency(totalRevenue)}</p>
          <p className="text-xs text-gray-500 mt-1">Verified payments only</p>
        </div>

        <div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm">
          <div className="flex items-center justify-between mb-2">
            <p className="text-sm font-medium text-gray-600">Active Properties</p>
            <Building2 className="size-5 text-purple-600" />
          </div>
          <p className="text-gray-900 text-2xl font-bold">{units.filter(u => u.available).length}</p>
          <p className="text-xs text-gray-500 mt-1">Out of {units.length} total units</p>
        </div>
      </div>

      {/* Quick Actions */}
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-6">
        <h2 className="mb-4 text-lg font-semibold text-gray-900">Quick Actions</h2>
        <div className="grid md:grid-cols-4 gap-4">
          <Link
            to="/admin/bookings"
            className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg hover:bg-yellow-100 transition-colors text-center group"
          >
            <div className="bg-yellow-600 text-white size-12 rounded-lg flex items-center justify-center mx-auto mb-2 text-xl font-bold shadow-sm">
              {pendingBookings.length}
            </div>
            <p className="text-sm font-medium text-yellow-800 group-hover:text-yellow-900">Approve Reservations</p>
          </Link>

          <Link
            to="/admin/payments"
            className="p-4 bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100 transition-colors text-center group"
          >
            <div className="bg-blue-600 text-white size-12 rounded-lg flex items-center justify-center mx-auto mb-2 text-xl font-bold shadow-sm">
              {pendingPayments.length}
            </div>
            <p className="text-sm font-medium text-blue-800 group-hover:text-blue-900">Verify Payments</p>
          </Link>

          <Link
            to="/admin/inquiries"
            className="p-4 bg-purple-50 border border-purple-200 rounded-lg hover:bg-purple-100 transition-colors text-center group"
          >
            <div className="bg-purple-600 text-white size-12 rounded-lg flex items-center justify-center mx-auto mb-2 text-xl font-bold shadow-sm">
              {openInquiries.length}
            </div>
            <p className="text-sm font-medium text-purple-800 group-hover:text-purple-900">Answer Inquiries</p>
          </Link>

          <Link
            to="/admin/properties"
            className="p-4 bg-green-50 border border-green-200 rounded-lg hover:bg-green-100 transition-colors text-center group"
          >
            <div className="bg-green-600 text-white size-12 rounded-lg flex items-center justify-center mx-auto mb-2 text-2xl font-bold shadow-sm">
              +
            </div>
            <p className="text-sm font-medium text-green-800 group-hover:text-green-900">Manage Properties</p>
          </Link>
        </div>
      </div>

      {/* Top Performing Properties */}
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-6">
        <h2 className="mb-4 text-lg font-semibold text-gray-900">Top Performing Units</h2>
        <div className="space-y-3">
          {unitBookings.map((unit, index) => (
            <div key={unit.id} className="flex items-center gap-4 p-3 bg-gray-50 border border-gray-100 rounded-lg hover:bg-gray-100 transition-colors">
              <div className="text-lg font-bold text-gray-400 w-8 text-center">#{index + 1}</div>
              {unit.images && unit.images.length > 0 ? (
                 <img src={unit.images[0]} alt={unit.name} className="size-12 object-cover rounded shadow-sm" />
              ) : (
                 <div className="size-12 bg-gray-200 rounded flex items-center justify-center">
                    <Building2 className="size-6 text-gray-400" />
                 </div>
              )}
              
              <div className="flex-1">
                <h3 className="text-sm font-semibold text-gray-900">{unit.name}</h3>
                <p className="text-xs font-medium text-gray-500">{unit.bookingCount} reservations</p>
              </div>
              <div className="text-right">
                <p className="text-green-700 font-bold">{formatCurrency(unit.revenue)}</p>
                <p className="text-xs font-medium text-gray-500">Gross Value</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Recent Bookings */}
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm">
        <div className="p-6 border-b border-gray-200 flex justify-between items-center">
          <h2 className="text-lg font-semibold text-gray-900">Recent Reservation Requests</h2>
          <Link to="/admin/bookings" className="text-sm font-medium text-blue-600 hover:text-blue-700 flex items-center gap-1">
            View all <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                <th className="px-6 py-3 text-xs font-semibold text-gray-600 uppercase tracking-wider">
                  Reservation ID
                </th>
                <th className="px-6 py-3 text-xs font-semibold text-gray-600 uppercase tracking-wider">
                  Property
                </th>
                <th className="px-6 py-3 text-xs font-semibold text-gray-600 uppercase tracking-wider">
                  Requested
                </th>
                <th className="px-6 py-3 text-xs font-semibold text-gray-600 uppercase tracking-wider">
                  Status
                </th>
                <th className="px-6 py-3 text-xs font-semibold text-gray-600 uppercase tracking-wider text-right">
                  Amount
                </th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-100">
              {recentBookings.length === 0 ? (
                <tr>
                  <td colSpan={5} className="px-6 py-8 text-center text-gray-500">
                    No recent reservations found in the database.
                  </td>
                </tr>
              ) : (
                recentBookings.map((booking) => {
                  return (
                    <tr key={booking.reservation_id} className="hover:bg-gray-50 transition-colors">
                      <td className="px-6 py-4 whitespace-nowrap text-xs font-mono text-gray-500">
                        {booking.reservation_id.split('-')[0]}...
                      </td>
                      <td className="px-6 py-4 text-sm font-medium text-gray-900">
                        {booking.title}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                        {new Date(booking.created_at).toLocaleDateString()}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                         <span className={`px-2.5 py-1 text-xs font-medium rounded-full border ${
                            booking.status === 'pending' ? 'bg-yellow-50 text-yellow-700 border-yellow-200' :
                            booking.status === 'approved' ? 'bg-blue-50 text-blue-700 border-blue-200' :
                            booking.status === 'confirmed' ? 'bg-green-50 text-green-700 border-green-200' :
                            booking.status === 'cancelled' ? 'bg-red-50 text-red-700 border-red-200' :
                            'bg-gray-50 text-gray-700 border-gray-200'
                          }`}>
                            {booking.status.toUpperCase()}
                          </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-bold text-gray-900 text-right">
                        {formatCurrency(Number(booking.total_amount))}
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Payment & Inquiries Summary */}
      <div className="grid md:grid-cols-2 gap-6">
        <div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm flex items-center justify-between group cursor-pointer hover:border-blue-300 transition-all">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-blue-100 rounded-xl group-hover:bg-blue-600 group-hover:text-white transition-colors">
              <Users className="size-6 text-blue-600 group-hover:text-white" />
            </div>
            <div>
              <p className="text-sm font-medium text-gray-600">Active Reservations</p>
              <p className="text-gray-900 text-xl font-bold">{approvedBookings.length}</p>
            </div>
          </div>
          <Link to="/admin/bookings" className="text-sm font-medium text-blue-600 flex items-center gap-1 group-hover:translate-x-1 transition-transform">
            Manage <ArrowRight className="w-4 h-4"/>
          </Link>
        </div>

         <div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm flex items-center justify-between group cursor-pointer hover:border-purple-300 transition-all">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-purple-100 rounded-xl group-hover:bg-purple-600 group-hover:text-white transition-colors">
              <Clock className="size-6 text-purple-600 group-hover:text-white" />
            </div>
            <div>
              <p className="text-sm font-medium text-gray-600">Awaiting Response</p>
              <p className="text-gray-900 text-xl font-bold">{openInquiries.length}</p>
            </div>
          </div>
          <Link to="/admin/inquiries" className="text-sm font-medium text-purple-600 flex items-center gap-1 group-hover:translate-x-1 transition-transform">
            View Inbox <ArrowRight className="w-4 h-4"/>
          </Link>
        </div>
      </div>
      
    </div>
  );
}